// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqhx6h2M4YMRK6IUwDG2iHQotaNDm1ddk',
    appId: '1:819757220267:web:2503e36c6f739aadcd92ee',
    messagingSenderId: '819757220267',
    projectId: 'trivio-8888',
    authDomain: 'trivio-8888.firebaseapp.com',
    storageBucket: 'trivio-8888.firebasestorage.app',
    measurementId: 'G-23VC95ZSE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYo6LMrmKRWxZIgq-xo6cGmvQQ8Js76M4',
    appId: '1:819757220267:android:505089b116c9a9b2cd92ee',
    messagingSenderId: '819757220267',
    projectId: 'trivio-8888',
    storageBucket: 'trivio-8888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zLMuAG2ul6-V03D_34elJvmsw_g3PtU',
    appId: '1:819757220267:ios:8c44647b93d05fbbcd92ee',
    messagingSenderId: '819757220267',
    projectId: 'trivio-8888',
    storageBucket: 'trivio-8888.firebasestorage.app',
    iosBundleId: 'com.example.registerPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zLMuAG2ul6-V03D_34elJvmsw_g3PtU',
    appId: '1:819757220267:ios:8c44647b93d05fbbcd92ee',
    messagingSenderId: '819757220267',
    projectId: 'trivio-8888',
    storageBucket: 'trivio-8888.firebasestorage.app',
    iosBundleId: 'com.example.registerPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqhx6h2M4YMRK6IUwDG2iHQotaNDm1ddk',
    appId: '1:819757220267:web:c7078dff1c59ccdacd92ee',
    messagingSenderId: '819757220267',
    projectId: 'trivio-8888',
    authDomain: 'trivio-8888.firebaseapp.com',
    storageBucket: 'trivio-8888.firebasestorage.app',
    measurementId: 'G-HVX0Q52BB5',
  );
}
